# Generated by Django 3.2.18 on 2023-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wxuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='唯一标识')),
                ('nickname', models.CharField(max_length=50, null=True, verbose_name='昵称')),
                ('gender', models.IntegerField(default=0, null=True, verbose_name='性别')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='城市')),
                ('province', models.CharField(max_length=50, null=True, verbose_name='省份')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='国家')),
                ('avatar_url', models.CharField(max_length=200, null=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
                'db_table': 'wx',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='wxuser',
            index=models.Index(fields=['openid'], name='wx_openid_6a1ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='wxuser',
            index=models.Index(fields=['nickname'], name='wx_nicknam_f05ee8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wxuser',
            unique_together={('openid',)},
        ),
    ]
